const images = {
  friends: require("./friends.png"),
  memories: require("./memories.png"),
  groups: require("./groups.png"),
  marketplace: require("./marketplace.png"),
  watch: require("./watch.png"),
  saved: require("./saved.png"),
  pages: require("./pages.png"),
  events: require("./events.png"),
  ad: require("./ad.png"),
  ads: require("./ads.png"),
  campus: require("./campus.png"),
  climate: require("./climate.png"),
  community: require("./community.png"),
  covid: require("./covid.png"),
  emotional: require("./emotional.png"),
  pay: require("./pay.png"),
  fav: require("./fav.png"),
  fund: require("./fund.png"),
  gaming: require("./gaming.png"),
  jobs: require("./jobs.png"),
  live: require("./live.png"),
  messenger: require("./messenger.png"),
  messkids: require("./messkids.png"),
  recent: require("./recent.png"),
  play: require("./play.png"),
  recentad: require("./recentad.png"),
  weather: require("./weather.png"),
};

export default images